# 排除因子配置文件
# 定义每个排除因子的规则和可选值

filter_factors:
  # 价格相关因子
  close:
    name: "收盘价"
    data_type: "numeric"
    operators: [ "gte", "lte"]  # 大于、小于、大于等于、小于等于
    value_options: [90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]  # 缩减from23to12
    default_range: 
      min_op: "gte"  # 默认大于等于
      min_val: 100
      max_op: "lte"  # 默认小于等于  
      max_val: 150
    max_conditions: 1  # 同一因子最多2个条件

  dblow:
    name: "双低"
    data_type: "numeric"
    operators: [ "gte", "lte"]  # 大于、小于、大于等于、小于等于
    value_options: [100, 120, 140, 160, 180, 200]  # 缩减from11to6
    default_range: 
      min_op: "gte"  # 默认大于等于
      min_val: 110
      max_op: "lte"  # 默认小于等于  
      max_val: 150
    max_conditions: 1  # 同一因子最多2个条件

  # 时间相关因子
  left_years:
    name: "剩余年限"
    data_type: "numeric" 
    operators: [ "gte", "lte"]
    value_options: [0.5, 1.5, 2.5]  # 缩减from6to3
    default_range:
      min_op: "gte"
      min_val: 0.5
      max_op: "lte" 
      max_val: 3
    max_conditions: 1

  list_days:
    name: "上市天数"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [1, 5, 10, 20, 45, 90, 180, 730]  # 缩减from16to8
    default_range:
      min_op: "gte"
      min_val: 4
      max_op: null  # 不设上限
      max_val: null
    max_conditions: 1

  # 交易相关因子
  amount:
    name: "成交额(万)"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [500, 1000, 2000, 5000, 10000, 20000]  # 缩减from11to6
    default_range:
      min_op: "gte"
      min_val: 1000
      max_op: null
      max_val: null
    max_conditions: 1

  vol:
    name: "成交量(手)"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [200, 1000, 5000, 20000, 50000]  # 缩减from9to5
    default_range:
      min_op: "gte"
      min_val: 1000
      max_op: null
      max_val: null
    max_conditions: 1

  turnover:
    name: "换手率"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [0.001, 0.01, 0.03, 0.08, 0.15, 0.3, 0.5, 0.8, 1.0, 1.5]  # 缩减from19to10
    default_range:
      min_op: "gte"
      min_val: 0.001
      max_op: null
      max_val: null
    max_conditions: 1

  # 估值相关因子
  conv_prem:
    name: "转股溢价率"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [-0.4, -0.2, 0, 0.2, 0.4, 0.6]  # 缩减from11to6
    default_range:
      min_op: "gte"
      min_val: 0.1
      max_op: "lte"
      max_val: 0.6
    max_conditions: 1

  pb:
    name: "市净率"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [0.5, 1.5, 2.5, 5, 10, 100]  # 缩减from12to6
    default_range:
      min_op: "gte"
      min_val: 1.5
      max_op: "lte"
      max_val: 10
    max_conditions: 1

  pe_ttm:
    name: "市盈率TTM"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [16, 30, 100, 1000, 10000, 50000, 100000]  # 缩减from14to7
    default_range:
      min_op: "gte"
      min_val: 16
      max_op: "lte"
      max_val: 50
    max_conditions: 1

  debt_to_assets:
    name: "资产负债率"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [0.2, 0.4, 0.6, 0.8, 1.0, 1.5]  # 缩减from11to6
    default_range:
      min_op: "gte"
      min_val: 0.1
      max_op: "lte"
      max_val: 1.5  # 修正: 从1.7改为1.5
    max_conditions: 1

  pct_chg:
    name: "涨跌幅"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [-0.6, -0.2, 0.1, 0.4, 0.8, 1.0]  # 缩减from11to6
    default_range:
      min_op: "gte"
      min_val: 0.1
      max_op: "lte"
      max_val: 1.0
    max_conditions: 1

  circ_mv:
    name: "正股流通市值(亿)"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [50, 150, 200, 500, 2500]  # 缩减from10to5
    default_range:
      min_op: "gte"
      min_val: 25
      max_op: "lte"
      max_val: 5500
    max_conditions: 1

  pct_chg_5:
    name: "5日涨跌幅"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [-0.9, -0.6, -0.3, 0, 0.005,0.01,0.02, 0.03, 0.5, 1,  1.2]
    default_range:
      min_op: "gte"
      min_val: 0
      max_op: "lte"
      max_val: 0.01
    max_conditions: 1

  pct_chg_5_stk:
    name: "正股5日涨跌幅"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [-0.7, -0.5, -0.3,  -0.1, 0, 0.1,  0.3, 0.5, 0.7, 0.9, 1.0, 1.2, 1.5]
    default_range:
      min_op: "gte"
      min_val: -0.1
      max_op: "lte"
      max_val: 0.1
    max_conditions: 1

  bias_5:
    name: "5日乖离率"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [-0.01, -0.005,  -0.003, -0.001, 0, 0.001, 0.003, 0.005, 0.006, 0.01]
    default_range:
      min_op: "gte"
      min_val: -0.005
      max_op: "lte"
      max_val: 0.006
    max_conditions: 1

  close_ma_5:
    name: "5日均价"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]  # 缩减from23to12
    default_range:
      min_op: "gte"
      min_val: 90
      max_op: "lte"
      max_val: 150
    max_conditions: 1

  alpha_pct_chg_5:
    name: "5日超额涨跌幅"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [-0.02, -0.01, 0, 0.01, 0.02, 0.03]  # 修正: 将1改为0
    default_range:
      min_op: "gte"
      min_val: -0.01
      max_op: "lte"
      max_val: 0.02
    max_conditions: 1

  turnover_5:
    name: "5日换手率"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [0.03, 0.05, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5]
    default_range:
      min_op: "gte"
      min_val: 0.03
      max_op: "lte"
      max_val: 0.3
    max_conditions: 1

  dv_ratio:
    name: "股息率"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [0.001, 0.003, 0.005, 0.007, 0.01, 0.015, 0.02]
    default_range:
      min_op: "gte"
      min_val: 0.003
      max_op: "lte"
      max_val: 0.01
    max_conditions: 1

  # ========== 第一阶段：核心因子配置 ==========
  # 以下配置基于可转债投资逻辑和行业经验生成

  # 核心估值因子 (4个)
  theory_conv_prem:
    name: "理论溢价率"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [-0.3, -0.1, 0, 0.1, 0.2, 0.3, 0.5, 0.8, 1.0]  # 缩减from17to9
    default_range:
      min_op: "gte"
      min_val: -0.1
      max_op: "lte"
      max_val: 0.5
    max_conditions: 1
    # 理论溢价率是核心估值指标，通常在-30%到50%之间，0附近需要密集分割

  mod_conv_prem:
    name: "修正溢价率"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [-0.2, -0.05, 0.05, 0.15, 0.25, 0.4, 0.6, 0.8]  # 缩减from15to8
    default_range:
      min_op: "gte"
      min_val: 0
      max_op: "lte"
      max_val: 0.4
    max_conditions: 1
    # 修正溢价率考虑了股息等因素，通常比理论溢价率略低

  bond_prem:
    name: "纯债溢价率"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [-0.4, -0.1, 0.1, 0.3, 0.5, 0.8, 1.5, 2.0]  # 缩减from15to8
    default_range:
      min_op: "gte"
      min_val: 0
      max_op: "lte"
      max_val: 1.0
    max_conditions: 1
    # 纯债溢价率反映相对纯债价值的溢价，通常为正值

  ytm:
    name: "到期收益率"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [-0.05, 0.01, 0.03, 0.05, 0.08, 0.12, 0.2, 0.3]  # 缩减from15to8
    default_range:
      min_op: "gte"
      min_val: 0
      max_op: "lte"
      max_val: 0.15
    max_conditions: 1
    # 到期收益率是重要的收益指标，通常在0-15%之间

  # 关键风险因子 (3个)
  # redeem_price_rate:
  #   name: "强赎触发价比率"
  #   data_type: "numeric"
  #   operators: [ "gte", "lte"]
  #   value_options: [0.7, 0.8, 0.85, 0.9, 0.95, 1.0, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.4, 1.5, 2.0]
  #   default_range:
  #     min_op: "gte"
  #     min_val: 0.8
  #     max_op: "lte"
  #     max_val: 1.3
  #   max_conditions: 1
    # 强赎触发价比率，通常在130%附近，是重要的风险指标

  # redeem_remain_days:
  #   name: "强赎剩余计数"
  #   data_type: "numeric"
  #   operators: [ "gte", "lte"]
  #   value_options: [0, 1, 3, 5, 7, 10, 15, 20, 30, 45, 60, 90, 180, 365, 999]
  #   default_range:
  #     min_op: "gte"
  #     min_val: 0
  #     max_op: "lte"
  #     max_val: 30
  #   max_conditions: 1
    # 强赎剩余天数，0表示可立即强赎，小值区间需要密集分割

  theory_bias:
    name: "理论偏离度"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [-0.2, -0.05, 0, 0.05, 0.15, 0.3, 0.5]  # 缩减from14to7
    default_range:
      min_op: "gte"
      min_val: -0.1
      max_op: "lte"
      max_val: 0.2
    max_conditions: 1
    # 理论偏离度反映实际价格相对理论价值的偏离程度

  # 核心价值因子 (4个)
  pure_value:
    name: "纯债价值"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [70, 85, 95, 105, 115, 130, 150]  # 缩减from14to7
    default_range:
      min_op: "gte"
      min_val: 80
      max_op: "lte"
      max_val: 120
    max_conditions: 1
    # 纯债价值提供下行保护，通常在80-120之间

  theory_value:
    name: "理论价值"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [80, 90, 95, 100, 105, 110, 115, 120, 125, 130, 140, 150, 160, 180, 200]
    default_range:
      min_op: "gte"
      min_val: 95
      max_op: "lte"
      max_val: 150
    max_conditions: 1
    # 理论价值是估值基准，通常在面值附近波动

  conv_value:
    name: "转股价值"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [70, 80, 90, 95, 100, 105, 110, 115, 120, 130, 140, 150, 160, 180, 200]
    default_range:
      min_op: "gte"
      min_val: 90
      max_op: "lte"
      max_val: 140
    max_conditions: 1
    # 转股价值反映转股后的价值，是核心参考指标

  option_value:
    name: "期权价值"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [0, 1, 2, 5, 8, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100]
    default_range:
      min_op: "gte"
      min_val: 5
      max_op: "lte"
      max_val: 50
    max_conditions: 1
    # 期权价值反映可转债的期权特性，通常为正值

  # ========== 第二阶段：重要补充因子配置 ==========
  # 规模流动性因子 + 补充估值因子

  # 规模流动性因子 (4个)
  issue_size:
    name: "发行规模(亿)"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 150, 200, 300, 500]
    default_range:
      min_op: "gte"
      min_val: 10
      max_op: "lte"
      max_val: 100
    max_conditions: 1
    # 发行规模影响流动性，通常在10-100亿之间

  remain_size:
    name: "剩余规模(亿)"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [2, 5, 8, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 150, 200]
    default_range:
      min_op: "gte"
      min_val: 5
      max_op: "lte"
      max_val: 80
    max_conditions: 1
    # 剩余规模反映未转股部分，影响后续流动性

  remain_cap:
    name: "剩余市值(亿)"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [5, 10, 15, 20, 30, 40, 50, 60, 80, 100, 120, 150, 200, 300, 500]
    default_range:
      min_op: "gte"
      min_val: 10
      max_op: "lte"
      max_val: 150
    max_conditions: 1
    # 剩余市值反映当前市场价值规模

  cap_mv_rate:
    name: "转债市占比"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [0.001, 0.005, 0.01, 0.02, 0.03, 0.05, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5, 0.8, 1.0]
    default_range:
      min_op: "gte"
      min_val: 0.01
      max_op: "lte"
      max_val: 0.3
    max_conditions: 1
    # 转债市值占正股市值比例，反映相对规模

  # 补充估值因子 (3个)
  ps_ttm:
    name: "市销率TTM"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [0.5, 1, 1.5, 2, 3, 4, 5, 6, 8, 10, 15, 20, 30, 50, 100]
    default_range:
      min_op: "gte"
      min_val: 1
      max_op: "lte"
      max_val: 20
    max_conditions: 1
    # 市销率补充PE/PB估值体系，适用于亏损公司

  total_mv:
    name: "正股总市值(亿)"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [20, 50, 80, 100, 150, 200, 300, 500, 800, 1000, 1500, 2000, 3000, 5000, 10000]
    default_range:
      min_op: "gte"
      min_val: 50
      max_op: "lte"
      max_val: 2000
    max_conditions: 1
    # 正股总市值反映公司整体规模，影响流动性和稳定性

  volatility:
    name: "年化波动率"
    data_type: "numeric"
    operators: [ "gte", "lte"]
    value_options: [0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5, 0.6, 0.8, 1.0, 1.2, 1.5, 2.0, 3.0]
    default_range:
      min_op: "gte"
      min_val: 0.2
      max_op: "lte" 
      max_val: 1.0
    max_conditions: 1
    # 年化波动率反映价格波动风险，通常在20%-100%之间

# 排除因子组合规则
combination_rules:
  max_factors: 6  # 缩减到最多8个排除因子 (第一阶段优化)
  max_combinations: 6000  # 硬性限制总组合数